<p align="center"><b><br>Aktivitas Partisipatif 1</b></br>
Agung Malik Ibrahim | SD04-B | 2311110067</p>

## Import Library

> Pada kode dibawah ini, kita melakukan import library yang akan kita gunakan. Library dalam konteks ini adalah kumpulan kode yang sudah dikompilasi dan dapat digunakan berulang kali dalam program yang berbeda. Disini kita menggunakan 3 library, yaitu pada baris pertama yang digunakan untuk mengimport/mengintegrasikan google colab supaya dapat terhubung dengan google drive. Lalu pada baris kedua kita mengimport library yang dinamakan `Pandas`. Library ini digunakan untuk mengolah data yang akan kita analisis. Lalu library yang ketiga kita menggunakan library dari `scikit-learn`. Library ini dapat kita gunakan untuk membantu kita dalam melakukan preprocessing data dan juga training model. Namun kita hanya akan menggunakanya untuk preprocessing data, yaitu normalisasi. Disini kita menggunakan `MinMaxScaler` untuk melakukan normalisasi data dan `LabelEncoder` untuk mengubah data object menjadi numerik.

In [ ]:
from google.colab import drive
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

drive.mount('/content/drive/')

Mounted at /content/drive/

## Memanggil Dataset

> Untuk memanggil dataset kita perlu membuat variable yang akan kita gunakan untuk menamai dataset kita. Disini saya membuat variable `df` yang didalamnya terdapat dataset yang akan kita olah datanya

In [ ]:
df = pd.read_excel('drive/MyDrive/dataset/CAD alizadeh.xls')

## Menampilkan Data

> Terdapat berbagai cara untuk menampilkan dataset, salahsatunya adalah dengan memanggil variable yang sudah kita buat. Karena saya membuat variable `df` maka kita hanya perlu menuliskan variable tersebut sehingga jika kita jalankan akan muncul tabel-tabel dataset tersebut

In [ ]:
df

,No,Age,Weight,Length,Sex,BMI,DM,HTN,Current Smoker,EX-Smoker,...,K,Na,WBC,Lymph,Neut,PLT,EF-TTE,Region RWMA,VHD,Cath
0,1,53,90,175,Male,29.387755,0,1,1,0,...,4.7,141,5700,39,52,261,50,0,N,Cad
1,2,67,70,157,Fmale,28.398718,0,1,0,0,...,4.7,156,7700,38,55,165,40,4,N,Cad
2,3,54,54,164,Male,20.077335,0,0,1,0,...,4.7,139,7400,38,60,230,40,2,mild,Cad
3,4,66,67,158,Fmale,26.838648,0,1,0,0,...,4.4,142,13000,18,72,742,55,0,Severe,Normal
4,5,50,87,153,Fmale,37.165193,0,1,0,0,...,4.0,140,9200,55,39,274,50,0,Severe,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,58,84,168,Male,29.761905,0,0,0,0,...,4.8,146,8500,34,58,251,45,0,N,Cad
299,300,55,64,152,Fmale,27.700831,0,0,0,0,...,4.0,139,11400,16,80,377,40,0,mild,Normal
300,301,48,77,160,Fmale,30.078125,0,1,0,0,...,4.0,140,9000,35,55,279,55,0,N,Normal
301,302,57,90,159,Fmale,35.599858,1,0,0,0,...,3.8,141,3800,48,40,208,55,0,N,Normal
302,303,56,85,170,Fmale,29.411765,0,1,1,0,...,4.4,147,6000,32,55,302,55,0,N,Cad

> Cara kedua yaitu dengan menambahkan `head` pada variable yang sudah kita buat. `head` digunakan untuk menampilkan data teratas. Pada code dibawah ini saya menuliskan `head(5)` yang artinya saya ingin menampilkan 5 data teratas dari dataset tersebut

In [ ]:
df.head(5)

,No,Age,Weight,Length,Sex,BMI,DM,HTN,Current Smoker,EX-Smoker,...,K,Na,WBC,Lymph,Neut,PLT,EF-TTE,Region RWMA,VHD,Cath
0,1,53,90,175,Male,29.387755,0,1,1,0,...,4.7,141,5700,39,52,261,50,0,N,Cad
1,2,67,70,157,Fmale,28.398718,0,1,0,0,...,4.7,156,7700,38,55,165,40,4,N,Cad
2,3,54,54,164,Male,20.077335,0,0,1,0,...,4.7,139,7400,38,60,230,40,2,mild,Cad
3,4,66,67,158,Fmale,26.838648,0,1,0,0,...,4.4,142,13000,18,72,742,55,0,Severe,Normal
4,5,50,87,153,Fmale,37.165193,0,1,0,0,...,4.0,140,9200,55,39,274,50,0,Severe,Normal

> Cara ketiga yang bisa kita gunakan yaitu menggunakan fungsi `tail`. Fungsi ini digunakan ketika kita ingin melihat kolom-kolom akhir dari dataset. Pada code ini saya menuliskan `tail(5)` yang artinya saya ingin menampilkan 5 data terakhir dari dataset ini

In [ ]:
df.tail(5)

,No,Age,Weight,Length,Sex,BMI,DM,HTN,Current Smoker,EX-Smoker,...,K,Na,WBC,Lymph,Neut,PLT,EF-TTE,Region RWMA,VHD,Cath
298,299,58,84,168,Male,29.761905,0,0,0,0,...,4.8,146,8500,34,58,251,45,0,N,Cad
299,300,55,64,152,Fmale,27.700831,0,0,0,0,...,4.0,139,11400,16,80,377,40,0,mild,Normal
300,301,48,77,160,Fmale,30.078125,0,1,0,0,...,4.0,140,9000,35,55,279,55,0,N,Normal
301,302,57,90,159,Fmale,35.599858,1,0,0,0,...,3.8,141,3800,48,40,208,55,0,N,Normal
302,303,56,85,170,Fmale,29.411765,0,1,1,0,...,4.4,147,6000,32,55,302,55,0,N,Cad

## Preprocessing data : memeriksa apakah ada yang kosong

> Disini kita diminta untuk memeriksa apakah ada data yang bernilai kosong. Kita bisa menggunakan fungsi yang sudah disediakan oleh library `Pandas`, yaitu `isnull` atau kita bisa menggunakan `isna`. Kedua code diatas bisa dapat kita gunakan untuk melihat dan memeriksa apakah dalam dataset yang kita miliki terdapat nilai yang kosong. Namun jika kita menggunakan code diatas saja maka hasil yang ditampilkan hanya bernilai `True` or `False` sehingga yang menyebabkan kita harus memeriksa satu per satu tabel apakah terdapat nilai `True`. Oleh karena itu, kita perlu menambahkan fungsi `sum` yang dapat membantu kita untuk meringkas ada beberapa nilai pada tabel dataset kita yang bernilai kosong/null, sehingga kita tidak perlu memeriksanya satu per satu. Jika kita jalankan kode dibawah ini akan menampilkan kolom tabel dan jumlah tabel yang bernilai kosong/null. Namun dari hasil yang sudah dijalankan tidak terdapat data yang bernilai kosong/null

In [ ]:
df.isnull().sum()

No                       0
Age                      0
Weight                   0
Length                   0
Sex                      0
BMI                      0
DM                       0
HTN                      0
Current Smoker           0
EX-Smoker                0
FH                       0
Obesity                  0
CRF                      0
CVA                      0
Airway disease           0
Thyroid Disease          0
CHF                      0
DLP                      0
BP                       0
PR                       0
Edema                    0
Weak Peripheral Pulse    0
Lung rales               0
Systolic Murmur          0
Diastolic Murmur         0
Typical Chest Pain       0
Dyspnea                  0
Function Class           0
Atypical                 0
Nonanginal               0
Exertional CP            0
LowTH Ang                0
Q Wave                   0
St Elevation             0
St Depression            0
Tinversion               0
LVH                      0
Poor R Progression       0
FBS                      0
CR                       0
TG                       0
LDL                      0
HDL                      0
BUN                      0
ESR                      0
HB                       0
K                        0
Na                       0
WBC                      0
Lymph                    0
Neut                     0
PLT                      0
EF-TTE                   0
Region RWMA              0
VHD                      0
Cath                     0
dtype: int64

## Mengubah semua kolom menjadi bernilai numerik

> Untuk mengubah semua kolom yang bernilai numerik langkah pertama yang perlu kita lakukan adalah mengetahui kolom mana yang mempunyai tipe data selain numerik. Data numerik adalah data yang berbentuk angka atau bilangan, dan merupakan bagian dari data kuantitatif. Data numerik pada python biasanya mempunyai tipe data `float` dan `int`. Untuk tipe data yang bertipe data non-numerik atau kategorikal biasanya mempunyai tipe data `object`. Untuk mengetahui hal tersebut kita bisa menggunakan fungsi `dtypes`. Jika kita jalankan maka akan muncul nama kolom dengan tipe data yang dimiliki oleh kolom tersebut

In [ ]:
df.dtypes

No                         int64
Age                        int64
Weight                     int64
Length                     int64
Sex                       object
BMI                      float64
DM                         int64
HTN                        int64
Current Smoker             int64
EX-Smoker                  int64
FH                         int64
Obesity                   object
CRF                       object
CVA                       object
Airway disease            object
Thyroid Disease           object
CHF                       object
DLP                       object
BP                         int64
PR                         int64
Edema                      int64
Weak Peripheral Pulse     object
Lung rales                object
Systolic Murmur           object
Diastolic Murmur          object
Typical Chest Pain         int64
Dyspnea                   object
Function Class             int64
Atypical                  object
Nonanginal                object
Exertional CP             object
LowTH Ang                 object
Q Wave                     int64
St Elevation               int64
St Depression              int64
Tinversion                 int64
LVH                       object
Poor R Progression        object
FBS                        int64
CR                       float64
TG                         int64
LDL                        int64
HDL                      float64
BUN                        int64
ESR                        int64
HB                       float64
K                        float64
Na                         int64
WBC                        int64
Lymph                      int64
Neut                       int64
PLT                        int64
EF-TTE                     int64
Region RWMA                int64
VHD                       object
Cath                      object
dtype: object

> Pada proses mengubah semua kolom menjadi bernilai numerik kita menggunakan `LabelEncoder`. `LabelEncoder` merupakan salahsatu metode yang digunakan untuk mengubah nilai nilai kategorikal menjadi numerik. Cara kerja `LabelEncoder` yaitu dengan mengubah data menjadi angka 0 sampai banyaknya data tersebut. Contohnya seperti pada gambar berikut ini

![](https://miro.medium.com/v2/resize:fit:802/1*J_GTKle7phrecheHa-sjYQ.png)

In [ ]:
obj = df[['Sex', 'Obesity', 'CRF', 'CVA', 'Airway disease', 'Thyroid Disease', 'CHF', 'DLP',
         'Weak Peripheral Pulse', 'Lung rales', 'Systolic Murmur', 'Diastolic Murmur', 'Dyspnea',
         'Atypical', 'Nonanginal', 'Exertional CP', 'LowTH Ang', 'LVH', 'Poor R Progression',
         'VHD', 'Cath']]

encoder = LabelEncoder()
df[['Sex', 'Obesity', 'CRF', 'CVA', 'Airway disease', 'Thyroid Disease', 'CHF', 'DLP',
         'Weak Peripheral Pulse', 'Lung rales', 'Systolic Murmur', 'Diastolic Murmur', 'Dyspnea',
         'Atypical', 'Nonanginal', 'Exertional CP', 'LowTH Ang', 'LVH', 'Poor R Progression',
         'VHD', 'Cath']] = df[['Sex', 'Obesity', 'CRF', 'CVA', 'Airway disease', 'Thyroid Disease', 'CHF', 'DLP',
         'Weak Peripheral Pulse', 'Lung rales', 'Systolic Murmur', 'Diastolic Murmur', 'Dyspnea',
         'Atypical', 'Nonanginal', 'Exertional CP', 'LowTH Ang', 'LVH', 'Poor R Progression',
         'VHD', 'Cath']].apply(encoder.fit_transform)

## Melakukan proses normalisasi pada masing-masing atribut

> Lalu kita melakukan proses normalisasi/scaling menggunakan MinMaxScaler. MinMaxScaler mengecilkan fitur menjadi range [0,1] atau [-1,1] apabila terdapat negative value. Tujuan dari scaling/normalisasi adalah untuk mengatasi masalah yang muncul dari skala yang berbeda dari fitur-fitur dalam data. Tanpa data scaling, algoritma machine learning dapat mengalami kesulitan dalam menemukan solusi yang optimal karena fitur-fitur yang memiliki skala yang berbeda akan memberikan bobot yang berbeda pada model.

In [ ]:
scaler = MinMaxScaler()

df = scaler.fit_transform(df)